### ISSUE TITLE
D365 Connection

### ISSUE THREAD

**Issue by joaopedromd** [justbetter/laravel-dynamics-client#16]
Hi there!
Thanks for your work. Been strugling with a connection with Dynamics 365 but still not abble to connect to server. Can you please specify the .env settings for 365 connection setup? What referes to tenant id, client id and secret.

tried many settings and getting this error:
`  HTTP request returned status code 401:
{"error":{"code":"Authentication_InvalidCredentials","message":"Web service access key is no longer supported as authent (truncated...)
`
best regards

**Comment by VincentBean** [comment]
We currently only support basic and NTLM authentication, we are aware that the new D365 uses OAuth2 but we do not have short term plans to add this to this package ourselves.

**Comment by VincentBean** [comment]
Added in #23
